name: Publish

on:
  push:
    branches:
      - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
        # extended: true
    - name: Build
      run: hugo --minify
    - name: Commit files
      run: |
        cd public
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "[action] Automated deployment"
    - name: Push commit
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      run: |
        cd output
        mkdir -p ~/.ssh
        eval "$(ssh-agent -s)"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add - <<< "${GIT_DEPLOY_KEY}"
        git remote -v
        git remote add conferences git@github.com:Conferences-Dev/Conferences-Dev.github.io.git
        ssh -Tv git@github.com || true
        git push -f conferences HEAD:main
